// app/components/CodeExporter.tsx
"use client";

import { useState } from "react";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import {
  Download,
  FileCode,
  FolderArchive,
  Copy,
  Check,
  FileJson,
  File,
} from "lucide-react";

interface CodeExporterProps {
  code: string;
  sketchImage?: string;
}

// 代码模板
const templates = {
  // Next.js App Router
  nextjs: (componentCode: string) => ({
    "app/page.tsx": componentCode,
    "app/layout.tsx": `
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Generated App',
  description: 'Generated by Sketch to React',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
`.trim(),
    "app/globals.css": `
@tailwind base;
@tailwind components;
@tailwind utilities;
`.trim(),
    "tailwind.config.js": `
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`.trim(),
    "postcss.config.js": `
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`.trim(),
    "package.json": JSON.stringify(
      {
        name: "generated-app",
        version: "0.1.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
        },
        dependencies: {
          next: "^14.0.0",
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          "lucide-react": "^0.294.0",
        },
        devDependencies: {
          "@types/node": "^20.0.0",
          "@types/react": "^18.2.0",
          "@types/react-dom": "^18.2.0",
          autoprefixer: "^10.4.16",
          postcss: "^8.4.31",
          tailwindcss: "^3.3.5",
          typescript: "^5.0.0",
        },
      },
      null,
      2,
    ),
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "es5",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [{ name: "next" }],
          paths: {
            "@/*": ["./*"],
          },
        },
        include: [
          "next-env.d.ts",
          "**/*.ts",
          "**/*.tsx",
          ".next/types/**/*.ts",
        ],
        exclude: ["node_modules"],
      },
      null,
      2,
    ),
    "README.md": `
# Generated React App

由 Sketch to React 自动生成

## 开始使用

\`\`\`bash
npm install
npm run dev
\`\`\`

打开 [http://localhost:3000](http://localhost:3000) 查看结果
`.trim(),
  }),

  // Vite + React
  vite: (componentCode: string) => ({
    "src/App.tsx": componentCode,
    "src/main.tsx": `
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`.trim(),
    "src/index.css": `
@tailwind base;
@tailwind components;
@tailwind utilities;
`.trim(),
    "index.html": `
<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generated App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`.trim(),
    "tailwind.config.js": `
/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`.trim(),
    "postcss.config.js": `
export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`.trim(),
    "vite.config.ts": `
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
})
`.trim(),
    "package.json": JSON.stringify(
      {
        name: "generated-app",
        private: true,
        version: "0.0.0",
        type: "module",
        scripts: {
          dev: "vite",
          build: "tsc && vite build",
          preview: "vite preview",
        },
        dependencies: {
          react: "^18.2.0",
          "react-dom": "^18.2.0",
          "lucide-react": "^0.294.0",
        },
        devDependencies: {
          "@types/react": "^18.2.0",
          "@types/react-dom": "^18.2.0",
          "@vitejs/plugin-react": "^4.2.0",
          autoprefixer: "^10.4.16",
          postcss: "^8.4.31",
          tailwindcss: "^3.3.5",
          typescript: "^5.2.2",
          vite: "^5.0.0",
        },
      },
      null,
      2,
    ),
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          module: "ESNext",
          skipLibCheck: true,
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
          strict: true,
          noUnusedLocals: true,
          noUnusedParameters: true,
          noFallthroughCasesInSwitch: true,
        },
        include: ["src"],
        references: [{ path: "./tsconfig.node.json" }],
      },
      null,
      2,
    ),
  }),

  // 纯组件
  component: (componentCode: string) => ({
    "Component.tsx": componentCode,
  }),
};

export default function CodeExporter({ code, sketchImage }: CodeExporterProps) {
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);

  // 复制代码
  const handleCopy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // 下载单个文件
  const handleDownloadFile = (filename: string, content: string) => {
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    saveAs(blob, filename);
  };

  // 下载完整项目
  const handleDownloadProject = async (template: "nextjs" | "vite") => {
    setExporting(true);

    try {
      const zip = new JSZip();
      const files = templates[template](code);

      // 添加所有文件
      Object.entries(files).forEach(([path, content]) => {
        zip.file(path, content);
      });

      // 添加原始草图（如果有）
      if (sketchImage) {
        const imageData = sketchImage.split(",")[1];
        zip.file("design/sketch.png", imageData, { base64: true });
      }

      // 生成并下载
      const blob = await zip.generateAsync({ type: "blob" });
      const projectName =
        template === "nextjs" ? "nextjs-project" : "vite-project";
      saveAs(blob, `${projectName}.zip`);
    } catch (error) {
      console.error("导出失败:", error);
    } finally {
      setExporting(false);
    }
  };

  // 导出 JSON 配置
  const handleExportJSON = () => {
    const config = {
      generatedAt: new Date().toISOString(),
      code,
      metadata: {
        framework: "react",
        styling: "tailwind",
        typescript: true,
      },
    };

    const blob = new Blob([JSON.stringify(config, null, 2)], {
      type: "application/json",
    });
    saveAs(blob, "component-config.json");
  };

  return (
    <div className="border rounded-lg overflow-hidden bg-white">
      {/* 头部 */}
      <div className="flex items-center justify-between p-3 bg-gray-50 border-b">
        <span className="font-medium text-sm">导出选项</span>
      </div>

      {/* 导出按钮组 */}
      <div className="p-4 space-y-4">
        {/* 快捷操作 */}
        <div className="grid grid-cols-2 gap-3">
          <button
            onClick={handleCopy}
            className="flex items-center justify-center gap-2 p-3 border rounded-lg hover:bg-gray-50 transition-colors"
          >
            {copied ? (
              <>
                <Check size={18} className="text-green-500" />
                <span className="text-green-500">已复制</span>
              </>
            ) : (
              <>
                <Copy size={18} />
                <span>复制代码</span>
              </>
            )}
          </button>

          <button
            onClick={() => handleDownloadFile("Component.tsx", code)}
            className="flex items-center justify-center gap-2 p-3 border rounded-lg hover:bg-gray-50 transition-colors"
          >
            <FileCode size={18} />
            <span>下载组件</span>
          </button>
        </div>

        {/* 分隔线 */}
        <div className="relative">
          <div className="absolute inset-0 flex items-center">
            <div className="w-full border-t"></div>
          </div>
          <div className="relative flex justify-center text-sm">
            <span className="px-2 bg-white text-gray-500">下载完整项目</span>
          </div>
        </div>

        {/* 项目模板 */}
        <div className="space-y-3">
          <button
            onClick={() => handleDownloadProject("nextjs")}
            disabled={exporting}
            className="w-full flex items-center gap-3 p-4 border rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50"
          >
            <div className="w-10 h-10 bg-black rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-lg">N</span>
            </div>
            <div className="flex-1 text-left">
              <div className="font-medium">Next.js 项目</div>
              <div className="text-sm text-gray-500">
                包含 App Router, Tailwind CSS, TypeScript
              </div>
            </div>
            <FolderArchive size={20} className="text-gray-400" />
          </button>

          <button
            onClick={() => handleDownloadProject("vite")}
            disabled={exporting}
            className="w-full flex items-center gap-3 p-4 border rounded-lg hover:bg-gray-50 transition-colors disabled:opacity-50"
          >
            <div className="w-10 h-10 bg-purple-500 rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-lg">⚡</span>
            </div>
            <div className="flex-1 text-left">
              <div className="font-medium">Vite 项目</div>
              <div className="text-sm text-gray-500">
                包含 React, Tailwind CSS, TypeScript
              </div>
            </div>
            <FolderArchive size={20} className="text-gray-400" />
          </button>
        </div>

        {/* 其他格式 */}
        <div className="flex gap-3">
          <button
            onClick={handleExportJSON}
            className="flex-1 flex items-center justify-center gap-2 p-2 text-sm border rounded hover:bg-gray-50"
          >
            <FileJson size={16} />
            导出 JSON
          </button>
        </div>
      </div>

      {/* 提示信息 */}
      <div className="px-4 py-3 bg-blue-50 border-t text-sm text-blue-700">
        💡 下载项目后，运行{" "}
        <code className="bg-blue-100 px-1 rounded">npm install</code> 和
        <code className="bg-blue-100 px-1 rounded">npm run dev</code> 即可启动
      </div>
    </div>
  );
}
